### ISSUE TITLE
Realm does not exist

### ISSUE THREAD

**Issue by pierre-josselin** [FIWARE/keycloak-vc-issuer#31]
Hi @pulledtim 

When I scan my QR code with the [Fiware Demo Wallet application](https://demo-wallet.fiware.dev/), I get the following error:

```json
{"error":"Realm does not exist"}
```

Here is what the QR code contains (truncated):

https://example.com/realms/4a0d5327-6bcc-42c5-a6fb-3e8587b00864/verifiable-credential/did:web:example.com/credential-offer

The realm name is wrong.

When I manually replace **4a0d5327-6bcc-42c5-a6fb-3e8587b00864** with **master**, I can get my verifiable credential:

https://example.com/realms/master/verifiable-credential/did:web:example.com/credential-offer

```json
{
    "credential_issuer": "https://example.com/realms/4a0d5327-6bcc-42c5-a6fb-3e8587b00864/verifiable-credential/did:web:example.com",
    "credentials": [
        {
            "type": "GaiaXParticipentCredential",
            "format": "ldp_vc"
        }
    ],
    "grants": {
        "urn:ietf:params:oauth:grant-type:pre-authorized_code": {
            "pre-authorized_code": "a.b.c",
            "user_pin_required": false
        }
    }
}
```

Plugin version: 1.0.0

Is it a bug? How to fix it?
Thank you

**Comment by beknazaresenbek** [comment]
Hi @pierre-josselin,

Master realm should not be used for creating a VC, you should access the VC generation page through your own realm. For example, if you have realm 'my-realm', then the URL of the VC generation page would be htttps://example.com/realms/my-realm/account/#/verifiable-credentials. Could you please try it?

By the way, please use the version 1.0.1, there was one bug in 1.0.0 (unrelated to this issue).

**Comment by pierre-josselin** [comment]
Hi @beknazaresenbek 

Thank you for your reply,

I confirm that I created a "vc-issuer" realm, recreated the clients and changed the plugin version to 1.0.1.

The verifiable credentials page is now:

https://keycloak.example.com/realms/vc-issuer/account/#/verifiable-credentials

The new QR code contains:

https://keycloak.example.com/realms/ac5e3b1b-d370-4e8f-83c3-9ec8ae0c8c64/verifiable-credential/did:web:example.com/credential-offer?credential_offer_uri=https%3A%2F%2Fkeycloak.example.com%2Frealms%2Fac5e3b1b-d370-4e8f-83c3-9ec8ae0c8c64%2Fverifiable-credential%2Fdid%3Aweb%3Aexample.com%2Fcredential-offer%2Fa.b.c

The realm name is still bad which returns "Realm does not exist"

**Comment by beknazaresenbek** [comment]
@pierre-josselin, ok, I see. Could you share the code, how to do create realm? If you are using Helm-Chart, could you show me the file realmConfigMap.yaml?

**Comment by pierre-josselin** [comment]
@beknazaresenbek 

Here is how I create the client:

POST /admin/realms/vc-issuer/clients

```json
{
  "clientId": "did:key:abc",
  "enabled": true,
  "description": "GaiaXParticipentCredential",
  "surrogateAuthRequired": false,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "defaultRoles": [],
  "redirectUris": [],
  "webOrigins": [],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": false,
  "serviceAccountsEnabled": false,
  "publicClient": false,
  "frontchannelLogout": false,
  "protocol": "SIOP-2",
  "attributes": {
     "expiryInMin": "3600",
     "vctypes_BatteryPassAuthCredential": "ldp_vc",
     "vc_subjectDid": "did:web:example.com",
     "BatteryPassAuthCredential_claims": "email,firstName,roles,subjectDid"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "defaultClientScopes": [],
  "optionalClientScopes": []
}
```

[Reference](https://github.com/FIWARE/keycloak-vc-issuer#protocol)

It could have something to do with Dennis note:

> As far as I know we didn't use the Keycloak API yet to add clients. For our test/demo deployments we directly provided the whole realm config during deployment.
> This is an example of one of our service consumers: https://github.com/FIWARE-Ops/fiware-gitops/blob/master/aws/dsba/happypets/keycloak/templates/realmConfigMap.yaml

**Comment by beknazaresenbek** [comment]
@pierre-josselin I see, so you've created it through UI. What is the realm's ID? Realm ID goes to the URL from QR-code, for example like this one: https://github.com/FIWARE-Ops/fiware-gitops/blob/723ba6421c35f05f25c9e720297087a2ad8cd894/aws/dsba/happypets/keycloak/templates/realmConfigMap.yaml#L8

**Comment by pierre-josselin** [comment]
@beknazaresenbek 

It looks like the realm ID is "vc-issuer":

From https://keycloak.example.com/admin/vc-issuer/console/#/vc-issuer/realm-settings

![Screenshot_20230829-130600~2.png](https://github.com/FIWARE/keycloak-vc-issuer/assets/70814177/fd206e76-5596-4f59-88ae-7fb7d88de537)

**Comment by beknazaresenbek** [comment]
@pierre-josselin ok, it would be great, if you could write me in Discord and show me the logs or demonstrate in real time

**Comment by beknazaresenbek** [comment]
As we discussed in Discord, turns out that creating realm through UI generates a random realm ID (which was then used in QR code). Even if UI says, that realm ID is 'vc-issuer', actually it was a name of the realm.

Maybe, it makes sense to use in QR code a name of the realm, instead of the ID. It would be a topic for discussion in my team. Thanks!
