### ISSUE TITLE
Discontinuation of Walt.id SSIKIT

### ISSUE THREAD

**Issue by Timizki** [FIWARE/keycloak-vc-issuer#36]
As walt.id has announced that theirs SSIKIT  is [discontinued ](https://github.com/walt-id/waltid-ssikit) from December 2023. I'm wondering how this will affect the keycloak-vc-issuer? 
Will keycloak-vc-issuer support other Walt.ID API's in the future to provide same functionalities?

**Comment by wistefan** [comment]
Hi, 
we are currently working on adding the functionality of the provider to the keycloak upstream. This is done without the SSIKit, thus the discontinuation will not have effects in the future. You can track the progress her: https://github.com/keycloak/keycloak/issues/25936
Once the functionality is available as at least as an experimental feature(most probably in keycloak release 24 or 25), we will also deprecate the keycloak-vc-issuer. Until then, the SSIKit has to be used as a temporary solution.
Best
